import http from 'k6/http';
import ws from 'k6/ws';
import { check, sleep } from 'k6';
import { SharedArray } from 'k6/data';

// --- CONFIGURATION ---
// 1. Ramp-up to 1000 users over 1 min
// 2. Hold 1000 users for 5 mins
// 3. Ramp-down to 0 over 30 seconds
export const options = {
    stages: [
        { duration: '1m', target: 1000 },
        { duration: '5m', target: 1000 },
        { duration: '30s', target: 0 },
    ],
    thresholds: {
        http_req_duration: ['p(95)<1000'], // 95% of requests must complete below 1s
        http_req_failed: ['rate<0.01'],    // Error rate must be less than 1%
    },
};

// --- DATA SOURCE ---
// Load CSV file generated by Laravel Command
const users = new SharedArray('Users Data', function () {
    const file = open('./users.csv');
    const rows = file.split('\n').filter(Boolean);
    // Skip header and parse
    return rows.slice(1).map(row => {
        const [user_id, email, attempt_id, exam_id, token] = row.split(',');
        return { user_id, email, attempt_id, exam_id, token };
    });
});

// --- BASE URL ---
// Change this to your target server address (e.g., http://127.0.0.1:8000)
const BASE_URL = __ENV.APP_URL || 'http://127.0.0.1:8000';
const WS_URL = __ENV.WS_URL || 'ws://127.0.0.1:8080/app/app-key'; // Reverb port 8080 usually

export default function () {
    // 1. Pick a random user from the CSV
    const user = users[Math.floor(Math.random() * users.length)];

    if (!user) {
        sleep(1);
        return;
    }

    // 2. HTTP AUTOSAVE SCENARIO
    const payload = JSON.stringify({
        attempt_id: user.attempt_id,
        exam_id: user.exam_id,
        question_id: Math.floor(Math.random() * 50) + 1,
        selected_option: ['A', 'B', 'C', 'D'][Math.floor(Math.random() * 4)],
        session_id: user.token
    });

    const params = {
        headers: {
            'Content-Type': 'application/json',
            'Accept': 'application/json',
            // If API needs auth, inject the Bearer token
            'Authorization': `Bearer ${user.token}`,
        },
    };

    const res = http.post(`${BASE_URL}/api/exam/save-answer`, payload, params);

    check(res, {
        'autosave status is 200': (r) => r.status === 200 || r.status === 201,
        'autosave success': (r) => {
            try {
                return JSON.parse(r.body).status === 'success';
            } catch (e) {
                return false;
            }
        }
    });

    // We simulate 5 seconds between each user's autosave
    sleep(5);
}
